version: '3.8'
services:
  web:
    build: .
    command: python manage.py runserver localhost:8000
    ports:
      - '8000:8000'
    env_file:
      - ./.env
#     nginx:
#       image: nginx
#       volumes:
#         - ./nginx/default.conf:/host_mnt/Users/admin/Desktop/nikita/123/diplom1/nginx/default.conf
#         - ./static:/code/static
#       ports:
#         - '80:80'
#       depends_on:
#         - web


